language: java
os:
  - linux
services:
  - docker
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
install:
  - ./gradlew assemble --stacktrace --info
script:
  - ./gradlew build verify javadocJar --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
