language: java
os:
  - linux
services:
  - docker
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

install:
  - travis_retry ./gradlew dependencies
script:
  - ./gradlew build verify javadocJar --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
