language: java
os:
  - linux
services:
  - docker
jdk:
  - oraclejdk9
  - openjdk10
  - openjdk11

install:
  - travis_retry ./gradlew --info :dependencies blackstrom-codec-jackson:dependencies blackstrom-codec-kryo:dependencies blackstrom-ledger-meteor:dependencies blackstrom-ledger-kafka:dependencies blackstrom-sim:dependencies --refresh-dependencies 
  - travis_retry docker pull obsidiandynamics/kafka
  - travis_retry docker pull postgres  

script:
  - ./gradlew build verify javadocJar --stacktrace --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
