version: "2"
services:
  kafka:
    image: obsidiandynamics/kafka
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"