version: "2"
services:
  kafka:
    image: obsidiandynamics/kafka
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: "LOCAL://:9092,DIND://:29092"
      KAFKA_ADVERTISED_LISTENERS: "LOCAL://localhost:9092,DIND://dind:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LOCAL:PLAINTEXT,DIND:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "LOCAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"